version: "4.3"

services:
    nginx:
        container_name: nginx-highload
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/hosts:/etc/nginx/conf.d
        depends_on:
            - apache2

    apache2:
        container_name: apache2-highload
        image: apache2-highload
        build:
            context: .
            dockerfile: docker/apache2/DockerFile
        volumes:
            - ./:/var/www
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal
            PHP_IDE_CONFIG: serverName=my.highload
