version: "4.3"

services:
    nginx:
        container_name: nginx-highload
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/hosts:/etc/nginx/conf.d
        depends_on:
            - apache2


    apache2:
        container_name: apache2-highload
        image: apache2-highload-image
        build:
            context: .
            dockerfile: docker/apache2/DockerFile
        volumes:
            - ./:/var/www
